title: Welcome to hell
description: it's been about a year since i updated this but what's good bby girl
google_analytics: UA-68480733-1
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
